# Generated by Django 4.1.3 on 2023-12-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_order_estimated_delivery_date_product_order_inpage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Collection",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.collection",
            ),
        ),
    ]
