# Generated by Django 4.1.3 on 2023-12-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collection_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Payment Left', 'Payment Left'), ('Order Place', 'Order Place'), ('Order recieved', 'Order recieved'), ('Making', 'Making'), ('Pickup', 'Pickup'), ('Dispatched', 'Dispatched'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=200),
        ),
    ]
